### ISSUE TITLE
sort on multiple dimensions?

### ISSUE THREAD

**Issue by SirZach** [Wildhoney/EmberCrossfilter#33]
I have set up a sortProperty but I want to set up a fallbackSortProperty to sort on if there are duplicates of the original property. Any suggestions on where to start?

**Comment by Wildhoney** [comment]
In which cases might there be duplicates of the original property?

**Comment by SirZach** [comment]
There may be multiple facts that have the same value for the sortProperty

**Comment by Wildhoney** [comment]
I see what you mean. Unfortunately it's not possible with Crossfilter. It uses its own internal sorting algorithm and doesn't accept a callback for sorting unlike JavaScript. Depending on the size of your collection, you could use Ember's `ArrayController` sort functionality, but I imagine you've tried this already and it's quite slow. The native JS `sort` is much quicker -- albeit not as quick as Crossfilter's, but could be acceptable if we're not talking thousands upon thousands of models.

**Comment by SirZach** [comment]
I figured out a trick...create a compound key property. Say the model looks like

```
a: DS.attr('string'),

b: DS.attr('string')
```

I created a

```
bTieBreaker: function () {
  return this.get('a') + this.get('b');
}.property('a', 'b')
```

And in the filterMap, I created bTieBreaker dimension.

This is working but I imagine there are limitations on what  kinds of properties can be used for compound keys.

**Comment by Wildhoney** [comment]
That's a creative idea! Although for example if one of your tiebreaker properties was a number, then that'd lose all meaning as it'd become a string, and the other thing is that you can't mix ascending with descending. How many models are we talking about? If it's not **that** many, then you could use the sorting in Ember?

**Comment by SirZach** [comment]
One of my tie breaker properties is a number but it happens to be a timestamp. I just make sure to get a new date object on the timestamp and then do a getTime() to guarantee all the number portions of the key are the same length. Varying lengths in numbers will really mess up sorting when they're converted to a string. But it I can successfully sort on descending and ascending.

I have about 1300 models and they'll continue to grow more. I used the default sorting at first but the delay was very noticeable, with crossfilter, it's much much faster.

**Comment by Wildhoney** [comment]
Absolutely! I'd be careful about loading too much data onto the client. You could take a look at my new project, which again uses Crossfilter so you'll be familiar with it, but it serves portions of data, and memorises the state of the filters, page number, per page, sort direction, et cetera...: https://github.com/Wildhoney/Snapshot.js -- the example of Snapshot uses 100,000 models and is super fast :+1:

**Comment by SirZach** [comment]
We have a Java backend but definitely something I'll keep an eye on. Thanks!
