### ISSUE TITLE
Ember 1.13

### ISSUE THREAD

**Issue by Leooo** [Wildhoney/EmberCrossfilter#41]
Hello thank you for sharing this.

I'm trying to make this work with Ember 1.12. Discovering crossFilter at the same type so this is step by step.

Not too difficult to create a own mixin in Ember-CLI replicating yours, and import crossfilter.js through bower.

Then Ember.ArrayController has been deprecated, so I just set the 'content' property to my array and changed a few bits and bobs to make it work with the 'content' array (some properties were defined on `this` as it was an arrayController, we need `this.get('content')` instead). Doesn't seem to work with promiseArray objects so I set up an observer to convert the promiseArray to a normal array. It refreshes when the store fetches new models, though I will have to check the performance of this later:

```
  //crossFilterArray is an alias for 'content'
  crossFilterArray:null,
  hasInitializedCrossFilterArray: false,
  _setCrossFilterArray: function(){
    if (!this.get('hasInitializedCrossFilterArray')) {
      this.set('hasInitializedCrossFilterArray',true);
      this.set("crossFilterArray",this.get("model").toArray());
    }
    else {
      var arr0=this.get("crossFilterArray");
      var arr1=this.get("model").toArray();
      var add=arr1.filter(function(x){return arr0.indexOf(x)===-1;});
      var rem=arr0.filter(function(x){return arr1.indexOf(x)===-1;});
      //TODO: update _createFilterBoolean on add/deleteRecords
      this.addRecords(add);
      this.deleteRecords(rem);
    }
  },
  _launchSetCrossFilterArray: function(){
    if (!this.get("model")) {return false;}
    Ember.run.scheduleOnce('destroy',this,'_setCrossFilterArray');
  }.observes('model.@each').on('init'),
```

The filters seem to work alright though using the debugging feature it seems to take 100/200 ms to filter regularly, which is strange given I only have some dozens of rows for now (maybe my dev browser is getting busy).

I have a question right now, I'm sure it can work but if someone had an Idea it could save me hours:

I used to be able to filter on hasMany relationships of my models: each model has many tags, and I want to filter on all the models which have those tags. Problem here is that I can not create a dimension in cross-filter as it must be a naturally-ordered value (i can not send an array of tags in _applyTags, I could send the number of tags for sorting, but for filtering it is not enough information). So there seems to be something missing, maybe the ability to define several properties for each row (one for each hasMany relationship), but in `_createFilterBoolean` there is only one property fetched per model..

**Comment by Leooo** [comment]
ok your "_createFilterBoolean" works well with "in Array" filter on hasMany relationships, with the following modifications:

```
  //LV: merge array of 'hasMany' into array of all relationships
  //removed:
  //var properties      = [].concat.apply([], allProperties).uniq();
  var properties=allProperties.reduce(function(prev,item){
    return [].concat.apply(prev, Ember.isArray(item) ? item.toArray() : [item]);
  },[]).uniq();
```

and:

```
  //var propertyValue = propertiesList[propertyIndex];
  var propertyValue = propertiesList.objectAt(propertyIndex);
```

Thanks again for sharing this.

**Comment by Leooo** [comment]
In case someone was looking to use a dynamic filter function instead of a fixed one 'filterFunction', this is in the code but not in the example:

```
      //filterVal setting from the user
      this.addFilter("keyword",function(name){
        return name.toLowerCase().indexOf(filterVal.toLowerCase())>-1;
      });
```

**Comment by Wildhoney** [comment]
@Leooo Looks as though you're making good progress without me :+1:

**Comment by Leooo** [comment]
Well It's just basic stuff, but maybe some help for the next one, feel free to close the issue.

**Comment by Leooo** [comment]
in sortContent, content was not updated:
`````
// Notify that we've rearranged the content, otherwise there will be no update.
          //changed    
          //this.notifyPropertyChange('content');
          this._applyContentChanges();
`````

Alright, I stop spamming the issue list now and closing the issue. Thanks for sharing.

**Comment by Leooo** [comment]
For other Ember users who may want to use crossfilter to replace reduceComputed:
- the sorting in crossfilter can only follow one dimension, so a bit tricky to create your own mixed sorting functions in crossfilter (https://github.com/square/crossfilter/issues/165), probably better to filter using crossfilter and then use Ember.computed.sort
-  more importantly: "The value returned by a dimension's accessor function for a given record should be deterministic and never change for the existence of the crossfilter.". This means properties refreshed on a row of the crossfilter array are not refreshed in the filter. So no way to use computed properties - only solution may be to observe the changes and deleteRecord/addRecord for the row.

**Comment by Leooo** [comment]
missing method to update Records:

```
      addRecord: function addRecord(record) {
          //LV: add back records previously deleted
          //https://github.com/square/crossfilter/issues/131
          if (this._deletedModels.contains(record)) {
            //not enough: we need to change in the reduce properties too
            //this._deletedModels.removeObject(record);
            this.updateRecord(record);
          }
          else {
            this._crossfilter.add([record]);
          }
          this._applyContentChanges();
          return true;
      },
     updateRecord: function(record){
        //_listener.startUpdate();
        //timer_begin("updateRecord");
        var c=this._crossfilter;
        this._liftAllFilters();
        var defaultDimension    = Ember.get(this, '_dimensionDefault'),
          self=this,
          deleted             = function(primaryKey) {
              return primaryKey===record.get("id");
          },
          contentToDelete             = defaultDimension.filterFunction(deleted).top(Infinity);
        c.remove();
        this._deletedModels.removeObject(record);
        this._restoreAllFilters();
        this.addRecord(record);//will revert defaultDimension to normal one
        //_listener.update();
        //timer_end("updateRecord");
        return true;
      },
      _liftAllFilters: function(){
        for (var key in this.filterMap) {
            if (!this.filterMap.hasOwnProperty(key)) {
                continue;
            }
            var map = this.filterMap[key],
            dimension   = this['_dimension%@'.fmt(map.dimension.capitalize())];
            dimension.filterAll();
        }
    return true;
      },
      _restoreAllFilters: function(){
        for (var key in this.filterMap) {
          var map = this.filterMap[key];
          this._updateContent(map);
        }
    return true;
      },
```
